### ISSUE TITLE
Upload APNs Authentication Key

### ISSUE THREAD

**Issue by lyndsey-ferguson** [AckeeCZ/fastlane-plugin-firebase_management#1]
Hello, this looks like a great plugin. I am trying to figure out how to use this, or the `api` class to upload an "APNs Authentication Key". I see that the current method expects a APNS Certificate with a password, but how do I upload the key?

Also, is there a way to detect if the key has already been uploaded so I don't upload unnecessarily?

**Comment by janmisar** [comment]
Hey, sorry for inactivity.

It's not possible to upload certificate or key with this plugin, because official API does not support it. Guys from Firebase promised me they will add it, but unfortunately nothing is happening 😞 

It's possible to add certificate using original plugin https://github.com/tkohout/fastlane-firebase-plugin by @tkohout, which uses unofficial API.

So this issue belongs rather there, or feel free to send there your PR with this feature 😉

**Comment by lyndsey-ferguson** [comment]
Thanks for getting back to me and posting an update. Bad news is better than no news.
